name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake lcov
          version: 1.0

      - name: Configure CMake with Coverage
        run: |
          cd tests
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: |
          cd tests
          cmake --build build

      - name: Run Tests
        run: |
          cd tests
          ./build/test_helpers

      - name: Generate Coverage Report
        run: |
          cd tests/build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '*/_deps/*' --output-file coverage.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./tests/build/coverage.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
